FROM python:3.12-slim

WORKDIR /app

COPY application/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY application/ .

EXPOSE 80

CMD ["gunicorn", "--bind", "0.0.0.0:80", "--workers", "2", "app:app"]